"""
Database models and schema for the trading engine.
"""
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Optional
import json


class TradeStatus(Enum):
    PENDING = "pending"           # Signal generated, awaiting OpenClaw
    APPROVED = "approved"         # OpenClaw approved
    REJECTED = "rejected"         # OpenClaw rejected
    EXECUTED = "executed"         # Order placed
    OPEN = "open"                 # Position is open
    CLOSED = "closed"             # Position closed
    FAILED = "failed"             # Execution failed


class TradeDirection(Enum):
    LONG = "long"
    SHORT = "short"


@dataclass
class TradeSignal:
    """Signal generated by a strategy."""
    id: Optional[int] = None
    strategy_name: str = ""
    symbol: str = ""
    direction: TradeDirection = TradeDirection.LONG
    entry_price: float = 0.0
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    trailing_stop_trigger: Optional[float] = None  # Profit ($) that triggers trailing stop
    trailing_stop_lock: Optional[float] = None    # Profit ($) to lock in when triggered
    confidence: float = 0.0
    reason: str = ""
    timestamp: datetime = field(default_factory=datetime.utcnow)
    metadata: dict = field(default_factory=dict)


@dataclass
class Trade:
    """A complete trade record."""
    id: Optional[int] = None
    signal_id: Optional[int] = None
    strategy_name: str = ""
    symbol: str = ""
    direction: TradeDirection = TradeDirection.LONG
    status: TradeStatus = TradeStatus.PENDING
    
    # Prices
    entry_price: float = 0.0
    exit_price: Optional[float] = None
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    
    # Position sizing
    quantity: float = 0.0
    leverage: float = 1.0
    
    # P&L
    pnl: Optional[float] = None
    pnl_percent: Optional[float] = None
    fees: float = 0.0

    # Trailing stop settings (set by strategy or user)
    trailing_stop_trigger: Optional[float] = None  # Profit ($) that triggers trailing stop
    trailing_stop_lock: Optional[float] = None    # Profit ($) to lock in when triggered
    trailing_stop_activated: bool = False         # Whether trailing stop has been activated

    # OpenClaw validation
    openclaw_approved: bool = False
    openclaw_analysis: str = ""
    openclaw_confidence: float = 0.0
    
    # Timestamps
    signal_time: datetime = field(default_factory=datetime.utcnow)
    approved_time: Optional[datetime] = None
    entry_time: Optional[datetime] = None
    exit_time: Optional[datetime] = None
    
    # Screenshots
    entry_screenshot: Optional[str] = None
    exit_screenshot: Optional[str] = None
    
    # Metadata
    metadata: dict = field(default_factory=dict)


@dataclass
class Position:
    """An open position."""
    id: Optional[int] = None
    trade_id: int = 0
    symbol: str = ""
    direction: TradeDirection = TradeDirection.LONG
    entry_price: float = 0.0
    quantity: float = 0.0
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    current_price: float = 0.0
    unrealized_pnl: float = 0.0
    opened_at: datetime = field(default_factory=datetime.utcnow)
    # Trailing stop
    trailing_stop_trigger: Optional[float] = None
    trailing_stop_lock: Optional[float] = None
    trailing_stop_activated: bool = False


@dataclass
class StrategyConfig:
    """Configuration for a loaded strategy."""
    name: str
    file_path: str
    enabled: bool = True
    symbols: list = field(default_factory=list)
    parameters: dict = field(default_factory=dict)
    last_modified: Optional[datetime] = None
    last_loaded: Optional[datetime] = None


# SQL Schema
SCHEMA_SQL = """
-- Trade signals from strategies
CREATE TABLE IF NOT EXISTS trade_signals (
    id SERIAL PRIMARY KEY,
    strategy_name VARCHAR(100) NOT NULL,
    symbol VARCHAR(20) NOT NULL,
    direction VARCHAR(10) NOT NULL,
    entry_price DECIMAL(20, 8) NOT NULL,
    stop_loss DECIMAL(20, 8),
    take_profit DECIMAL(20, 8),
    confidence DECIMAL(5, 4),
    reason TEXT,
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    metadata JSONB DEFAULT '{}'
);

-- Main trades table
CREATE TABLE IF NOT EXISTS trades (
    id SERIAL PRIMARY KEY,
    signal_id INTEGER REFERENCES trade_signals(id),
    strategy_name VARCHAR(100) NOT NULL,
    symbol VARCHAR(20) NOT NULL,
    direction VARCHAR(10) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    
    entry_price DECIMAL(20, 8) NOT NULL,
    exit_price DECIMAL(20, 8),
    stop_loss DECIMAL(20, 8),
    take_profit DECIMAL(20, 8),
    
    quantity DECIMAL(20, 8) NOT NULL DEFAULT 0,
    leverage DECIMAL(5, 2) DEFAULT 1,
    
    pnl DECIMAL(20, 8),
    pnl_percent DECIMAL(10, 4),
    fees DECIMAL(20, 8) DEFAULT 0,
    
    openclaw_approved BOOLEAN DEFAULT FALSE,
    openclaw_analysis TEXT,
    openclaw_confidence DECIMAL(5, 4),
    
    signal_time TIMESTAMPTZ NOT NULL,
    approved_time TIMESTAMPTZ,
    entry_time TIMESTAMPTZ,
    exit_time TIMESTAMPTZ,
    
    entry_screenshot VARCHAR(500),
    exit_screenshot VARCHAR(500),

    trailing_stop_trigger DECIMAL(20, 8),
    trailing_stop_lock DECIMAL(20, 8),
    trailing_stop_activated BOOLEAN DEFAULT FALSE,

    metadata JSONB DEFAULT '{}'
);

-- Open positions
CREATE TABLE IF NOT EXISTS positions (
    id SERIAL PRIMARY KEY,
    trade_id INTEGER REFERENCES trades(id),
    symbol VARCHAR(20) NOT NULL,
    direction VARCHAR(10) NOT NULL,
    entry_price DECIMAL(20, 8) NOT NULL,
    quantity DECIMAL(20, 8) NOT NULL,
    stop_loss DECIMAL(20, 8),
    take_profit DECIMAL(20, 8),
    current_price DECIMAL(20, 8),
    unrealized_pnl DECIMAL(20, 8),
    opened_at TIMESTAMPTZ DEFAULT NOW(),
    trailing_stop_trigger DECIMAL(20, 8),
    trailing_stop_lock DECIMAL(20, 8),
    trailing_stop_activated BOOLEAN DEFAULT FALSE
);

-- Strategy configurations
CREATE TABLE IF NOT EXISTS strategy_configs (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) UNIQUE NOT NULL,
    file_path VARCHAR(500) NOT NULL,
    enabled BOOLEAN DEFAULT TRUE,
    symbols TEXT[] DEFAULT '{}',
    parameters JSONB DEFAULT '{}',
    last_modified TIMESTAMPTZ,
    last_loaded TIMESTAMPTZ
);

-- Performance metrics (daily aggregates)
CREATE TABLE IF NOT EXISTS daily_performance (
    id SERIAL PRIMARY KEY,
    date DATE NOT NULL,
    strategy_name VARCHAR(100),
    symbol VARCHAR(20),
    total_trades INTEGER DEFAULT 0,
    winning_trades INTEGER DEFAULT 0,
    losing_trades INTEGER DEFAULT 0,
    total_pnl DECIMAL(20, 8) DEFAULT 0,
    win_rate DECIMAL(5, 4),
    avg_win DECIMAL(20, 8),
    avg_loss DECIMAL(20, 8),
    max_drawdown DECIMAL(20, 8),
    UNIQUE(date, strategy_name, symbol)
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_trades_status ON trades(status);
CREATE INDEX IF NOT EXISTS idx_trades_symbol ON trades(symbol);
CREATE INDEX IF NOT EXISTS idx_trades_strategy ON trades(strategy_name);
CREATE INDEX IF NOT EXISTS idx_trades_signal_time ON trades(signal_time);
CREATE INDEX IF NOT EXISTS idx_positions_symbol ON positions(symbol);
CREATE INDEX IF NOT EXISTS idx_signals_timestamp ON trade_signals(timestamp);
"""


def init_database(conn):
    """Initialize the database schema."""
    cur = conn.cursor()
    cur.execute(SCHEMA_SQL)

    # Migration: Add trailing_stop columns if they don't exist
    try:
        cur.execute("""
            ALTER TABLE trades
            ADD COLUMN IF NOT EXISTS trailing_stop_trigger DECIMAL(20, 8),
            ADD COLUMN IF NOT EXISTS trailing_stop_lock DECIMAL(20, 8),
            ADD COLUMN IF NOT EXISTS trailing_stop_activated BOOLEAN DEFAULT FALSE
        """)
    except Exception:
        pass  # Columns may already exist

    try:
        cur.execute("""
            ALTER TABLE positions
            ADD COLUMN IF NOT EXISTS trailing_stop_trigger DECIMAL(20, 8),
            ADD COLUMN IF NOT EXISTS trailing_stop_lock DECIMAL(20, 8),
            ADD COLUMN IF NOT EXISTS trailing_stop_activated BOOLEAN DEFAULT FALSE
        """)
    except Exception:
        pass  # Columns may already exist

    conn.commit()
    cur.close()
    print("[DB] Schema initialized")
